### ISSUE TITLE
建议优化粘贴版内容自带换行问题

### ISSUE THREAD

**Issue by whiter001** [yoggy/pbcopy#1]
完全复现了系统命令的功能，非常赞！
只是echo abc | pbcopy 得到的粘贴内容自带换行功能，虽然很棒，很多时候能省事少按那么一下，不过，还是有那么一些情况是不想要换行的，比如配合fzf拿到的地址做移动复制命令操作的时候等等。

**Comment by yoggy** [comment]
I cannot read Chinese. Please use English or Japanese...
